### ISSUE TITLE
Feature: Dependency Management with Pipenv or Poetry

### ISSUE THREAD

**Issue by RyanDoesMath** [Paper-Chart-Extraction-Project/ChartExtractor#25]
This issue proposes introducing a dependency manager manage the project's growing list of dependencies. Dependencies will be listed in a central location (Pipfile or Poetry.lock) for easy tracking and version control. Managing dependencies will then become a single command away, ensuring everyone has the correct versions. When someone clones the repository, they can quickly set up the environment with consistent dependencies.

**Proposed Solutions:**

The two most popular options for python dependency management are:

  -  ([**Pipenv:**](https://pipenv.pypa.io/en/latest/installation.html)) simpler option
  -  ([**Poetry:**](https://python-poetry.org/)) more feature rich option

Whoever takes this issue should research both briefly before implementing one of them in a new branch and linking the PR here for discussion.

**Comment by charbelmarche33** [comment]
I decided to move forward with poetry. Watched several videos about it and looked into the differences between pipenv and poetry--aside from containing more features, it's apparently a faster and more stable dependency resolver. I will be implementing these changes today.

**Comment by charbelmarche33** [comment]
### Some instructions for getting set up:

- Install poetry using pip to start
  ```bash
  pip install poetry
  ```
- I have created the pyproject.toml files so you don't have to worry about any of that. Just do the below.
- Add configuration to have venv in project directory
  ```bash
  poetry config virtualenvs.in-project true
  ```
- Set up venv using poetry
  ```bash
  poetry install
  ```
- Now you should have a created venv that you can switch into with the following command and run the python scripts
  ```bash
  poetry shell
  ```

Pull request is [here](https://github.com/Paper-Chart-Extraction-Project/ChartExtractor/pull/27)

**Comment by charbelmarche33** [comment]
Also heads up the linked PR field is not editable for some reason... I may be doing something wrong but I don't think I'm able to link it.

**Comment by charbelmarche33** [comment]
As discussed in the PR, `poetry install` must be followed by the `--no-root` flag
